import { PhilosophyPrinciple, HowIBuildItem, ContactLink, CurrentlyItem } from './types';

export const philosophyConfig: PhilosophyPrinciple[] = [
  {
    icon: 'cube',
    title: 'Metadata-Driven',
    description: 'Every component, page, and configuration is driven by typed metadata — enabling automatic validation, documentation generation, and AI-assisted tooling.',
  },
  {
    icon: 'hashtag',
    title: 'Config-First',
    description: 'Single-source-of-truth configuration files power the entire application. Changing one config value propagates everywhere without touching templates or controllers.',
  },
  {
    icon: 'code',
    title: 'AI-Assisted Delivery',
    description: 'Design contracts generated by AI tools are consumed directly by implementation agents, creating a repeatable, auditable delivery pipeline.',
  },
];

export const bioParagraphs: string[] = [
  "I'm a full-stack developer and technical lead who believes the best software comes from systems thinking — designing not just components, but the pipelines, tools, and conventions that produce them. My engineering philosophy centers on three principles: metadata-driven architecture, config-first design, and AI-assisted delivery.",
  'With a First-class degree in Computer Engineering and years of experience leading teams at enterprise scale, I build platforms that are maintainable, testable, and documented by default. I specialize in Angular, Node.js, Python, and cloud infrastructure — but more importantly, I specialize in building the systems that build software.',
  'This portfolio itself is a demonstration of that philosophy. Every page, section, and interaction is driven by typed configuration objects. The design was generated by AI design tools, implemented by AI coding agents, and orchestrated by reusable system tooling. It\'s a living case study in metadata-driven engineering.',
];

export const howIBuildConfig: HowIBuildItem[] = [
  {
    icon: 'gears',
    title: 'OOP Class-Based Services',
    description: 'All business logic lives in typed, injectable service classes with single responsibilities. No fat components, no inline data fetching.',
  },
  {
    icon: 'code',
    title: 'Universal Component Wrappers',
    description: 'Reusable presentation components accept typed config inputs. The same card component renders projects, certificates, or experience entries by switching config sources.',
  },
  {
    icon: 'hashtag',
    title: 'Single-Source-of-Truth Config',
    description: 'Configuration objects define all copy, routing, and data. Static configs are the default; a generated JSON file can optionally override them field-by-field without breaking.',
  },
  {
    icon: 'robot',
    title: 'AI-Augmented Workflows',
    description: 'PRDs to Design to Prompts to Code. Each step produces an artifact consumed by the next. This reduces context-switching and ensures design intent survives to implementation.',
  },
];

export const contactLinksConfig: ContactLink[] = [
  { label: 'GitHub', url: 'https://github.com/Sotonye0808', icon: 'github' },
  { label: 'LinkedIn', url: 'https://www.linkedin.com/in/sotonye-dagogo-bb6585255', icon: 'linkedin' },
  { label: 'Email', url: 'mailto:sotydagz@gmail.com', icon: 'email' },
  { label: 'X / Twitter', url: 'https://x.com/therealsoshady', icon: 'x' },
];

export const currentlyConfig: CurrentlyItem[] = [
  { label: 'Availability', value: 'Open to opportunities' },
  { label: 'Current Role', value: 'Technical Lead at HICC & Founder' },
  { label: 'Location', value: 'Nigeria · Remote' },
];
