import { ProjectEntry } from './types';

const enterpriseProjects: ProjectEntry[] = [
  {
    image: 'enterpriseProjects/transact.jpg',
    title: 'Transact Store',
    description: 'Multi-vendor e-commerce platform connecting users to premium products and services across Africa.',
    githubLink: undefined,
    liveLink: 'https://transact-store.web.app',
    techStack: ['Angular', 'TypeScript', 'Tailwind', 'Firebase', 'NodeJS'],
    featured: true,
    isCaseStudy: true,
    tier: 'flagship',
  },
  {
    image: 'enterpriseProjects/signature-app.jpg',
    title: 'Signature App',
    description: 'A web application for creating, managing, and verifying digital signatures with e-signature workflows.',
    githubLink: undefined,
    liveLink: 'https://signature-eu.web.app',
    techStack: ['Angular', 'Django', 'Tailwind', 'Firebase', 'Python', 'TypeScript'],
    isCaseStudy: true,
    tier: 'flagship',
  },
  {
    image: 'enterpriseProjects/roxos-ornaments.jpg',
    title: "Roxo's Ornaments",
    description: 'E-commerce platform for unique jewelry and accessories with payment processing and inventory management.',
    githubLink: undefined,
    liveLink: 'https://roxos-ornaments.web.app',
    techStack: ['Angular', 'TypeScript', 'Tailwind', 'Firebase', 'NodeJS', 'Django'],
    isCaseStudy: true,
    tier: 'flagship',
  },
];

const frameworksProjects: ProjectEntry[] = [
  {
    image: 'frameworksLibrariesProjects/task-tracker-2.jpg',
    title: 'Task Tracker App',
    description: 'A task tracking application built with Next.js featuring usage statistics and real-time updates.',
    githubLink: 'https://github.com/Sotonye0808/task-tracker-2',
    liveLink: 'https://task-tracker-2.vercel.app/',
    techStack: ['NextJS', 'TypeScript', 'Bootstrap'],
    tier: 'applied',
  },
  {
    image: 'frameworksLibrariesProjects/random-quote-machine.jpg',
    title: 'Random Quote Machine',
    description: 'A React-based quote generator with Twitter sharing and a clean responsive interface.',
    githubLink: 'https://github.com/Sotonye0808/randomQuoteMachine',
    liveLink: 'https://sotonye0808.github.io/randomQuoteMachine/',
    techStack: ['React', 'JavaScript', 'Bootstrap'],
    tier: 'applied',
  },
  {
    image: 'enterpriseProjects/weather-app.png',
    title: 'Weather App',
    description: 'A progressive web app providing real-time weather for cities worldwide, with offline support and favorites.',
    githubLink: 'https://github.com/Sotonye0808/weather-app',
    liveLink: 'https://meteor08.netlify.app/',
    techStack: ['React', 'Redux', 'TypeScript', 'CSS'],
    tier: 'applied',
  },
  {
    image: 'enterpriseProjects/company-mgmt.png',
    title: 'Company Management App',
    description: 'A web application for managing company information with offline capabilities and dark/light theme.',
    githubLink: 'https://github.com/Sotonye0808/company-mgmt',
    liveLink: 'https://company-mgmt-three.vercel.app/',
    techStack: ['NextJS', 'Redux', 'TypeScript', 'GraphQL'],
    tier: 'applied',
  },
  {
    image: 'frameworksLibrariesProjects/drum-machine.jpg',
    title: 'Drum Machine',
    description: 'Interactive drum machine built with React, supporting keyboard and click-based sound triggering.',
    githubLink: 'https://github.com/Sotonye0808/drumMachine',
    liveLink: 'https://sotonye0808.github.io/drumMachine/',
    techStack: ['React', 'JavaScript', 'Bootstrap'],
    tier: 'applied',
  },
  {
    image: 'frameworksLibrariesProjects/js-clock.jpg',
    title: '25 + 5 Clock',
    description: 'A Pomodoro-style timer application with customizable work and break intervals.',
    githubLink: 'https://github.com/Sotonye0808/js-clock',
    liveLink: 'https://sotonye0808.github.io/js-clock/',
    techStack: ['React', 'JavaScript', 'Bootstrap'],
    tier: 'applied',
  },
  {
    image: 'frameworksLibrariesProjects/javascript-calculator.jpg',
    title: 'JavaScript Calculator',
    description: 'A fully functional calculator with keyboard support and chainable operations.',
    githubLink: 'https://github.com/Sotonye0808/javascriptCalculator',
    liveLink: 'https://sotonye0808.github.io/javascriptCalculator/',
    techStack: ['React', 'JavaScript', 'Bootstrap'],
    tier: 'applied',
  },
  {
    image: 'frameworksLibrariesProjects/markdown-previewer.jpg',
    title: 'Markdown Previewer',
    description: 'A real-time markdown editor and previewer with live HTML rendering.',
    githubLink: 'https://github.com/Sotonye0808/markdownPreviewer',
    liveLink: 'https://sotonye0808.github.io/markdownPreviewer/',
    techStack: ['React', 'JavaScript', 'Bootstrap'],
    tier: 'applied',
  },
  {
    image: 'frameworksLibrariesProjects/portfolio-website.jpg',
    title: 'Portfolio Website',
    description: 'My personal portfolio built with Angular, showcasing projects, skills, and certifications.',
    githubLink: 'https://github.com/Sotonye0808/portfolio-website',
    liveLink: 'https://sotonye-dagogo.is-a.dev/',
    techStack: ['Angular', 'TypeScript', 'Tailwind'],
    tier: 'applied',
  },
];

const pythonProjects: ProjectEntry[] = [
  {
    image: 'pythonProjects/ann.jpg',
    title: 'Sentiment Analysis using Transfer Learning',
    description: 'Fine-tuned AfriBERTa model for sentiment analysis of Yorùbá text, providing emotion detection for African language content.',
    githubLink: 'https://github.com/Sotonye0808/ann-project',
    liveLink: 'https://github.com/Sotonye0808/ann-project',
    techStack: ['Python', 'Transformers', 'NLP'],
    tier: 'applied',
  },
  {
    image: 'pythonProjects/dbm-package.jpg',
    title: 'MySQL Database Manager Package',
    description: 'A Python package for performing CRUD operations and complex SQL queries on MySQL databases.',
    githubLink: 'https://github.com/Sotonye0808/DBM_package',
    liveLink: 'https://sotonye0808.github.io/DBM_package/',
    techStack: ['Python', 'MySQL', 'SQL'],
    tier: 'applied',
  },
];

const earlyProjects: ProjectEntry[] = [
  {
    image: 'basicHtmlCssJsProjects/ecommerce-webproj.jpg',
    title: 'E-commerce Landing Page',
    description: 'A responsive e-commerce landing page built with vanilla HTML, CSS, and JavaScript.',
    githubLink: 'https://github.com/Sotonye0808/eCommerceWebProj',
    liveLink: 'https://sotonye0808.github.io/eCommerceWebProj/',
    techStack: ['HTML5', 'CSS', 'JavaScript'],
    tier: 'archive',
  },
  {
    image: 'basicHtmlCssJsProjects/countdown-timer.jpg',
    title: 'Countdown Timer',
    description: 'A customizable countdown timer for tracking time until specific events.',
    githubLink: 'https://github.com/Sotonye0808/valCountdownProject',
    liveLink: 'https://sotonye0808.github.io/valCountdownProject/',
    techStack: ['HTML5', 'CSS', 'JavaScript'],
    tier: 'archive',
  },
  {
    image: 'basicHtmlCssJsProjects/palindrome-checker.jpg',
    title: 'Palindrome Checker',
    description: 'A utility for checking if words or phrases are palindromes.',
    githubLink: 'https://github.com/Sotonye0808/palindromeChecker',
    liveLink: 'https://sotonye0808.github.io/palindromeChecker/',
    techStack: ['HTML5', 'CSS', 'JavaScript'],
    tier: 'archive',
  },
  {
    image: 'basicHtmlCssJsProjects/telephone-validator.jpg',
    title: 'Telephone Number Validator',
    description: 'Validates US telephone numbers using regex patterns.',
    githubLink: 'https://github.com/Sotonye0808/telephoneNumberValidator',
    liveLink: 'https://sotonye0808.github.io/telephoneNumberValidator/',
    techStack: ['HTML5', 'CSS', 'JavaScript'],
    tier: 'archive',
  },
  {
    image: 'basicHtmlCssJsProjects/roman-converter.jpg',
    title: 'Roman Numeral Converter',
    description: 'Converts between Arabic numbers and Roman numerals.',
    githubLink: 'https://github.com/Sotonye0808/romanNumeralConverter',
    liveLink: 'https://sotonye0808.github.io/romanNumeralConverter/',
    techStack: ['HTML5', 'CSS', 'JavaScript'],
    tier: 'archive',
  },
  {
    image: 'basicHtmlCssJsProjects/webdev-practice.jpg',
    title: 'Web Development Practice',
    description: 'A collection of early web development practice projects and experiments.',
    githubLink: 'https://github.com/Sotonye0808/web_dev_practice',
    liveLink: 'https://sotonye0808.github.io/web_dev_practice/',
    techStack: ['HTML5', 'CSS', 'JavaScript'],
    tier: 'archive',
  },
  {
    image: 'miniProjects/pokemon-search.jpg',
    title: 'Pokemon Search App',
    description: 'A Pokemon search application displaying stats, abilities, and sprites.',
    githubLink: 'https://github.com/Sotonye0808/pokemonSearchApp',
    liveLink: 'https://sotonye0808.github.io/pokemonSearchApp/',
    techStack: ['HTML5', 'CSS', 'JavaScript'],
    tier: 'archive',
  },
  {
    image: 'miniProjects/grid-magazine.jpg',
    title: 'FreeCodeCamp Magazine',
    description: 'A responsive magazine layout demonstrating CSS Grid techniques.',
    githubLink: 'https://github.com/Sotonye0808/gridMagazine',
    liveLink: 'https://sotonye0808.github.io/gridMagazine/',
    techStack: ['HTML5', 'CSS'],
    tier: 'archive',
  },
  {
    image: 'miniProjects/bar-chart.jpg',
    title: 'GDP Bar Chart',
    description: 'A D3.js bar chart visualizing US and Nigeria GDP data.',
    githubLink: 'https://github.com/Sotonye0808/barChart',
    liveLink: 'https://sotonye0808.github.io/barChart/',
    techStack: ['HTML5', 'CSS', 'JavaScript', 'D3JS'],
    tier: 'archive',
  },
  {
    image: 'miniProjects/heat-map.jpg',
    title: 'Global Temperature Heat Map',
    description: 'A D3.js heat map visualizing monthly global land-surface temperatures.',
    githubLink: 'https://github.com/Sotonye0808/heatMap',
    liveLink: 'https://sotonye0808.github.io/heatMap/',
    techStack: ['HTML5', 'CSS', 'JavaScript', 'D3JS'],
    tier: 'archive',
  },
  {
    image: 'miniProjects/city-skyline.jpg',
    title: 'City Skyline',
    description: 'A responsive CSS art piece featuring a city skyline with day/night modes.',
    githubLink: 'https://github.com/Sotonye0808/citySkyline',
    liveLink: 'https://sotonye0808.github.io/citySkyline/',
    techStack: ['HTML5', 'CSS'],
    tier: 'archive',
  },
  {
    image: 'miniProjects/penguin-transforms.jpg',
    title: 'Penguin via Transforms',
    description: 'A CSS art project building a penguin using transform properties.',
    githubLink: 'https://github.com/Sotonye0808/penguinViaTransforms',
    liveLink: 'https://sotonye0808.github.io/penguinViaTransforms/',
    techStack: ['HTML5', 'CSS'],
    tier: 'archive',
  },
  {
    image: 'miniProjects/nutrition-label.jpg',
    title: 'Nutrition Label',
    description: 'A CSS-styled nutrition facts label mimicking FDA guidelines.',
    githubLink: 'https://github.com/Sotonye0808/nutritionLabel',
    liveLink: 'https://sotonye0808.github.io/nutritionLabel/',
    techStack: ['HTML5', 'CSS'],
    tier: 'archive',
  },
  {
    image: 'miniProjects/ferris-wheel.jpg',
    title: 'Ferris Wheel',
    description: 'A CSS-animated ferris wheel demonstrating keyframe animations.',
    githubLink: 'https://github.com/Sotonye0808/ferrisWheel',
    liveLink: 'https://sotonye0808.github.io/ferrisWheel/',
    techStack: ['HTML5', 'CSS'],
    tier: 'archive',
  },
];

export const flagshipConfig = enterpriseProjects;
export const appliedConfig = [...frameworksProjects, ...pythonProjects];
export const archiveConfig = earlyProjects;
export const allProjects: ProjectEntry[] = [...flagshipConfig, ...appliedConfig, ...archiveConfig];

export function getProjectsByTier(tier: 'flagship' | 'applied' | 'archive'): ProjectEntry[] {
  return allProjects.filter(p => p.tier === tier);
}
