import { TechItem } from './types';

export const techStackConfig: TechItem[] = [
  { name: 'TypeScript', color: '#3178C6', icon: 'typescript-original.svg' },
  { name: 'JavaScript', color: '#F7DF1E', icon: 'javascript-original.svg' },
  { name: 'Node.js', color: '#339933', icon: 'nodejs-original-wordmark.svg' },
  { name: 'Angular', color: '#DD0031', icon: 'angular-original.svg' },
  { name: 'Python', color: '#4479A1', icon: 'python-original-wordmark.svg' },
  { name: 'React', color: '#764ABC', icon: 'react-original-wordmark.svg' },
  { name: 'Django', color: '#E0234E', icon: 'django-plain-wordmark.svg' },
  { name: 'HTML5', color: '#1572B6', icon: 'html5-original.svg' },
  { name: 'Git', color: '#F05032', icon: 'git-original-wordmark.svg' },
  { name: 'Firebase', color: '#F24E1E', icon: 'firebase-plain-wordmark.svg' },
  { name: 'Tailwind', color: '#38B2AC', icon: 'tailwindcss-original.svg' },
  { name: 'MongoDB', color: '#47A248', icon: 'mongodb-original-wordmark.svg' },
  { name: 'Supabase', color: '#3ECF8E', icon: 'supabase-original.svg' },
  { name: 'Sentry', color: '#362D59', icon: 'sentry-original-wordmark.svg' },
  { name: 'Express', color: '#000000', icon: 'express-original-wordmark.svg' },
  { name: 'MySQL', color: '#4479A1', icon: 'mysql-original-wordmark.svg' },
  { name: 'Redis', color: '#DC382D', icon: 'redis-original-wordmark.svg' },
  { name: 'Docker', color: '#2496ED', icon: 'docker-original-wordmark.svg' },
  { name: 'NextJS', color: '#000000', icon: 'nextjs-original-wordmark.svg' },
  { name: 'GraphQL', color: '#E10098', icon: 'graphql-plain-wordmark.svg' },
  { name: 'PostgreSQL', color: '#336791', icon: 'postgresql-original-wordmark.svg' },
  { name: 'CI/CD', color: '#2088FF', icon: 'githubactions-original-wordmark.svg' },
];